version: "3.8"
services:
  my_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  freelance_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:changelog-master.yaml
    depends_on:
      - my_db